version: '3'
services:
  app:
    build: .
    ports:
      - "8011:8011"
    depends_on:
      - mongo
    environment:
      - PORT=8011
      - MONGO_URI=mongodb://mongo:27017/tokyo_life_dev
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
